main: studio.fractures.yuhutils.Main
name: yuhutils
version: '3.4.0'
author: frykher
api-version: '1.16'
description: yuhutils adds discord integration and coordinates-related commands as utility


softdepend: [SuperVanish, PremiumVanish]

commands:
  sharecoords:
    description: Shares your current coordinates with the user of your choice.
    usage: /sharecoords <playerName>
  requestcoords:
    description: Request the coordinates of another online player of your choice.
    usage: /requestcoords <playerName>
  savecoords:
    description: Save coordinates with a unique name along with a specified dimension and coordinates. You can just
      provide a name and "@s" to save your current coordinates with no extra args.
    usage: /savecoords <unique-name> <@s (use @s if you want to save your current coords) | dimension> <x?> <y?> <z?>
  viewcoords:
    description: View all saved coordinates saved with the savecoords command.
    usage: /viewcoords
